[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ceceo_llvm_parser = { path = "../parser" }
clap = { version = "4.0.29", features = ["derive"] }